name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
    push:
        branches: [ "main" ]
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
